spring.application.name=uco-parking-backend
server.port=8080

db.url=jdbc:sqlserver://localhost:1433;databaseName=ucoparking;encrypt=false;trustServerCertificate=true
db.user=sa
db.password=TuPassword
db.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver