USE ucoparking;
GO

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.TABLES
    WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Pais'
)
BEGIN
    CREATE TABLE dbo.Pais (
        id   UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
        nombre NVARCHAR(200)  NOT NULL,
        CONSTRAINT PK_Pais PRIMARY KEY (id)
    );
END
GO
